### ISSUE TITLE
Record stream

### ISSUE THREAD

**Issue by rastaxe** [personalrobotics/k2_server#2]
Hi, I want to use this package and I am wondering if it Is possible to record streams with the server in order to use the client/server programs without the real sensor.
Is it also possible to use rviz to display the point clouds?

**Comment by ajakhotia** [comment]
Hi
    It is indeed possible to record streams and use it as an input to the client, but you will need to fake the server that will send the prerecorded stream to the client. However, if the purpose is to use the stream for some subsequent processing and visualization in rviz then making a rosbag is the easiest thing to do. Does that work for you?
