### ISSUE TITLE
RGB stream corrupted

### ISSUE THREAD

**Issue by soulslicer** [personalrobotics/k2_server#4]
If I enable the RGB stream on the k2_client, the depth stream starts to lag, and the RGB stream looks corrupted and laggy. Is there a particular solution for this?

**Comment by psigen** [comment]
Hmm, this might be a format version mismatch in the latest versions of server and client.  Thanks for reporting, let me investigate a bit more.

**Comment by hsvoen** [comment]
I am also noticing this, it seems like the the buffer for the RGB image is written to while it is being sent over TCP. Did you make any progress on this issue?
