### ISSUE TITLE
Post build copy failure in k2_server

### ISSUE THREAD

**Issue by PyryM** [personalrobotics/k2_server#8]
Severity    Code    Description Project File    Line    Suppression State
Error       The command "xcopy “C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0\ExtensionSDKs\Microsoft.Kinect.Face\2.0\Redist\CommonConfiguration\x64\NuiDatabase” “NuiDatabase” /e /y /i /r" exited with code 4.   Kinect2Server

**Comment by Raziel90** [comment]
check if the output folder is read only, i solved manually copying the NuiDatabase folder
